[book]
title = "The Rust Programming Language"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css", "theme/pagetoc.css"]
additional-js = ["ferris.js", "theme/pagetoc.js"]
git-repository-url = "https://github.com/rust-lang/book"

[preprocessor.theme]
pagetoc = true
sidebar-width = "280px"
content-max-width = "75%"
content-main-margin-left = "5%"
content-main-margin-right = "5%"
root-font-size = "80%" 
sidebar-font-size = "0.85em"

